// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package storage

import (
	"database/sql"
)

type Pr struct {
	ID                       int64
	ReviewStatus             string
	Url                      string
	Title                    string
	Author                   string
	RepoName                 string
	RepoOwner                string
	RepoUrl                  string
	IsDraft                  bool
	LastUpdated              string
	LastPrCommenter          string
	UnrespondedThreads       int64
	Additions                int64
	Deletions                int64
	ReviewRequestedFromUsers string
	Buried                   sql.NullBool
}
