// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package storage

import (
	"context"
)

const getPr = `-- name: GetPr :one
select id, review_status, url, title, author, repo_name, repo_owner, repo_url, is_draft, last_updated, last_pr_commenter, unresponded_threads, additions, deletions, review_requested_from_users, buried from prs where id = ? limit 1
`

func (q *Queries) GetPr(ctx context.Context, id int64) (Pr, error) {
	row := q.db.QueryRowContext(ctx, getPr, id)
	var i Pr
	err := row.Scan(
		&i.ID,
		&i.ReviewStatus,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.RepoName,
		&i.RepoOwner,
		&i.RepoUrl,
		&i.IsDraft,
		&i.LastUpdated,
		&i.LastPrCommenter,
		&i.UnrespondedThreads,
		&i.Additions,
		&i.Deletions,
		&i.ReviewRequestedFromUsers,
		&i.Buried,
	)
	return i, err
}
